# Generated by Django 5.1.5 on 2025-02-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.PositiveIntegerField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('MarksId', models.AutoField(primary_key=True, serialize=False)),
                ('TotalMarks', models.PositiveIntegerField()),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('AdmissionId', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfAdmission', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
