# Generated by Django 5.1.5 on 2025-02-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='TotalMarks',
        ),
        migrations.AddField(
            model_name='marks',
            name='Subject1',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
