# Generated by Django 5.1.6 on 2025-02-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0004_remove_admission_studentid_remove_marks_studentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.student'),
        ),
    ]
