# Generated by Django 5.1.6 on 2025-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0005_alter_admission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
