# Generated by Django 5.1.6 on 2025-02-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0006_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdmissionId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.admission'),
        ),
    ]
